autoDetectedPackages:
- com.alibaba.dubbo.cache
- com.alibaba.dubbo.common
- com.alibaba.dubbo.config
- com.alibaba.dubbo.container
- com.alibaba.dubbo.monitor
- com.alibaba.dubbo.qos.command
- com.alibaba.dubbo.registry
- com.alibaba.dubbo.remoting
- com.alibaba.dubbo.rpc
- com.alibaba.dubbo.validation
- com.example.test
- com.pojo
- com.service
- demo
- org.apache.dubbo.aot.generate
- org.apache.dubbo.auth
- org.apache.dubbo.cache
- org.apache.dubbo.common
- org.apache.dubbo.config
- org.apache.dubbo.container
- org.apache.dubbo.demo
- org.apache.dubbo.dependency
- org.apache.dubbo.echo
- org.apache.dubbo.filter
- org.apache.dubbo.gen
- org.apache.dubbo.graalvm.demo
- org.apache.dubbo.maven.plugin
- org.apache.dubbo.metadata
- org.apache.dubbo.metrics
- org.apache.dubbo.monitor
- org.apache.dubbo.qos
- org.apache.dubbo.reactive
- org.apache.dubbo.registry
- org.apache.dubbo.remoting
- org.apache.dubbo.rpc
- org.apache.dubbo.security.cert
- org.apache.dubbo.serialization
- org.apache.dubbo.service
- org.apache.dubbo.spring.boot
- org.apache.dubbo.spring.security.filter
- org.apache.dubbo.spring.security.jackson
- org.apache.dubbo.spring.security.model
- org.apache.dubbo.spring.security.utils
- org.apache.dubbo.springboot.demo
- org.apache.dubbo.test.check
- org.apache.dubbo.test.common
- org.apache.dubbo.test.spring
- org.apache.dubbo.validation
- po
enableAutoDetect: true
funcDisplayConfig:
  skipConstructors: false
  skipFieldAccess: true
  skipFieldChange: true
  skipGetters: true
  skipNonProjectPackages: true
  skipPrivateMethods: false
  skipSetters: true
ignoreSameClassCall: null
ignoreSamePackageCall: null
includedPackagePrefixes: null
includedParentClasses: null
name: xcodemap-filter
recordMode: smart
sourceDisplayConfig:
  color: blue
startOnDebug: false
